esphome:
  name: ledtest
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "testlight Fallback Hotspot"
    password: "6151awvulG"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password

ota:
  password: !secret password

# Example configuration entry
light:
  - platform: neopixelbus
    type: GRBW
    pin: GPIO3
    num_leds: 4
    name: "test Light"